apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.storage }}
  {{- if .Values.mysql.storageClass }}
  storageClassName: {{ .Values.mysql.storageClass }}
  {{- end }}
