apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  mysql-root-password: {{ .Values.mysql.rootPassword }}
  mysql-database: {{ .Values.mysql.database }}
  mysql-user: {{ .Values.mysql.user }}
  mysql-password: {{ .Values.mysql.password }}
