apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: default
data:
  WP_HOME: "http://wordpress.44.209.163.179.nip.io"
  WP_SITEURL: "http://wordpress.44.209.163.179.nip.io"
